### ISSUE TITLE
这边不应该去写入rec.Category, 会导致崩溃

### ISSUE THREAD

**Issue by huangapple** [jeanphorn/log4go#13]
pattlog.go 第92行， 你这个rec是传给不止一个goroutine, 是指针传递， 所以在任何goroutine都不要无锁写入， 要不会导致崩溃。

**Comment by yangyongzhen** [comment]
这个panic是什么原因导致的呢？使用中又遇到一个导致崩溃的问题
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x455c82]

goroutine 4 [running]:
bytes.(*Buffer).WriteString(0xc043212850, 0x0, 0x7, 0x3, 0x3, 0x0)
        D:/Go/src/bytes/buffer.go:188 +0xb1
github.com/jeanphorn/log4go.FormatLogRecord(0x6e6a0f, 0x19, 0xc04339fc70, 0x1, 0x1)
        D:/GOPATH/src/github.com/jeanphorn/log4go/pattlog.go:94 +0x3d6
github.com/jeanphorn/log4go.(*ConsoleLogWriter).run(0xc0420022e0, 0x716a80, 0xc042076008)
        D:/GOPATH/src/github.com/jeanphorn/log4go/termlog.go:34 +0x77
created by github.com/jeanphorn/log4go.NewConsoleLogWriter
        D:/GOPATH/src/github.com/jeanphorn/log4go/termlog.go:26 +0xc6
exit status 2

**Comment by yangyongzhen** [comment]
收到！多谢啦，我试试
